#!/usr/bin/sh

# --- AUTOSTARTS ---
riverctl spawn "swaybg -i ~/.config/river/nord_lake.png -m fill"
riverctl spawn "mako > /dev/null 2>&1"
riverctl spawn "dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP=river"
riverctl spawn "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
#riverctl spawn "~/.config/river/autolock.sh"
riverctl spawn "i3-battery-popup -n -L 30 -m 'Battery Low!'"
riverctl spawn "waybar"

# --- LAYOUTS ---
riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.5 &

# --- RULES ---
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id 'galculator' float
riverctl rule-add -app-id 'imv' float

# --- LAPTOP ---
riverctl keyboard-layout it
riverctl set-repeat 50 300
riverctl input pointer-1267-12442-ELAN2203:00_04F3:309A_Touchpad tap enabled
riverctl input pointer-1267-12442-ELAN2203:00_04F3:309A_Touchpad natural-scroll enabled
riverctl focus-follows-cursor normal

# --- DISPLAYS ---

# --- SHORTCUTS --- 
riverctl map normal Super X spawn alacritty
riverctl map normal Super B spawn thorium-browser
riverctl map normal Super R spawn "rofi -show drun"
riverctl map normal Super E spawn thunar
riverctl map normal Super+Control L spawn "/home/thrp/.config/river/lock_screen.sh"
riverctl map normal Super P spawn 'grim ~/Pictures/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send -t 2000 "Screenshot taken" | wl-copy'
riverctl map normal Super+Shift P spawn 'grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send -t 2000 "Screenshot taken"| wl-copy'

# --- KEYBINDINGS ---
riverctl map normal Super+Shift Q exit
riverctl map normal Super Q close

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# --- TAGS ---
for i in $(seq 1 6)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags

    riverctl map normal Super+Shift $i set-view-tags $tags

    riverctl map normal Super+Control $i toggle-focused-tags $tags

    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# --- LAPTOP KEYBINDINGS ---
for mode in normal locked
do

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    riverctl map $mode None XF86AudioMicMute      spawn 'pamixer --default-source --toggle-mute'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

done

